# Generated by Django 3.1.3 on 2020-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='班级名称')),
                ('teacher_id', models.IntegerField(verbose_name='代课教师')),
                ('number', models.IntegerField(verbose_name='学生人数')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='教师姓名')),
                ('lesson_name', models.CharField(max_length=16, verbose_name='可以教授的课程')),
            ],
        ),
    ]
